@ECHO OFF

SET INSTALL_UTIL=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\InstallUtil.exe

SET BIN_DIR=..\bin

SET DEBUG_DIR=%BIN_DIR%\Debug
SET RELEASE_DIR=%BIN_DIR%\Release

SET VFS_SERVICE_NAME=VirtualFileSystem.WindowsService.exe

SET VFS_SERVICE_PATH_DEBUG=%DEBUG_DIR%\%VFS_SERVICE_NAME%
SET VFS_SERVICE_PATH_RELEASE=%RELEASE_DIR%\%VFS_SERVICE_NAME%

SET UNINST_KEY=/u
